export enum Operations{
    CLEAR = 'CLEAR',
    DELETE = 'DELETE',
    MULTIPLY = 'MULTIPLY',
    DIVIDE = 'DIVIDE',
    ADD = 'ADD',
    SUBTRACT = 'SUBTRACT',
    APPEND_NUMBER = 'APPEND_NUMBER',
    APPEND_POINT = 'APPEND_POINT',
    CALCULATE = 'CALCULATE',
}